/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Intefaz;

import Algebra.AplicacionesA;
import Algebra.MatricesA;
import Algebra.TeoriaA;
import Funciones.AplicacionesF;
import Funciones.TeoriaF;
import Funciones.GraficadorF;
import Trigonometria.AplicacionesT;
import Trigonometria.TeoriaT;
import Trigonometria.TrianguloInteractivoT;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.JOptionPane;

/**
 *
 * @author OMCG1
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public MenuPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        GENERAL = new javax.swing.JMenu();
        SIIT = new javax.swing.JMenuItem();
        INFO = new javax.swing.JMenuItem();
        SALIR = new javax.swing.JMenuItem();
        FUNCIONES = new javax.swing.JMenu();
        TEORIAF = new javax.swing.JMenuItem();
        APLICACIONESF = new javax.swing.JMenuItem();
        GRAFICADORA = new javax.swing.JMenuItem();
        TRIGONOMETRIA = new javax.swing.JMenu();
        TEORIAT = new javax.swing.JMenuItem();
        APLICACIONEST = new javax.swing.JMenuItem();
        TRIANGULOI = new javax.swing.JMenuItem();
        ALGEBRA = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Navegador");
        setResizable(false);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gif.gif"))); // NOI18N

        GENERAL.setText("General");

        SIIT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/globo.png"))); // NOI18N
        SIIT.setText("Ingresar a SIIT");
        SIIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIITActionPerformed(evt);
            }
        });
        GENERAL.add(SIIT);

        INFO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ayuda.png"))); // NOI18N
        INFO.setText("Acerca de...");
        INFO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INFOActionPerformed(evt);
            }
        });
        GENERAL.add(INFO);

        SALIR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SALIDA.png"))); // NOI18N
        SALIR.setText("Salir");
        SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALIRActionPerformed(evt);
            }
        });
        GENERAL.add(SALIR);

        jMenuBar1.add(GENERAL);

        FUNCIONES.setText("Funciones");

        TEORIAF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/revista-abierta.png"))); // NOI18N
        TEORIAF.setText("Teoria");
        TEORIAF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEORIAFActionPerformed(evt);
            }
        });
        FUNCIONES.add(TEORIAF);

        APLICACIONESF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lapiz.png"))); // NOI18N
        APLICACIONESF.setText("Aplicaciones");
        APLICACIONESF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                APLICACIONESFActionPerformed(evt);
            }
        });
        FUNCIONES.add(APLICACIONESF);

        GRAFICADORA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/grafico.png"))); // NOI18N
        GRAFICADORA.setText("Graficadora");
        GRAFICADORA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GRAFICADORAActionPerformed(evt);
            }
        });
        FUNCIONES.add(GRAFICADORA);

        jMenuBar1.add(FUNCIONES);

        TRIGONOMETRIA.setText("Trigonometría");

        TEORIAT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/revista-abierta.png"))); // NOI18N
        TEORIAT.setText("Teoria");
        TEORIAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEORIATActionPerformed(evt);
            }
        });
        TRIGONOMETRIA.add(TEORIAT);

        APLICACIONEST.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lapiz.png"))); // NOI18N
        APLICACIONEST.setText("Aplicaciones");
        APLICACIONEST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                APLICACIONESTActionPerformed(evt);
            }
        });
        TRIGONOMETRIA.add(APLICACIONEST);

        TRIANGULOI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/triangulo.png"))); // NOI18N
        TRIANGULOI.setText("Triángulo interactivo");
        TRIANGULOI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TRIANGULOIActionPerformed(evt);
            }
        });
        TRIGONOMETRIA.add(TRIANGULOI);

        jMenuBar1.add(TRIGONOMETRIA);

        ALGEBRA.setText("Álgebra lineal");

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/revista-abierta.png"))); // NOI18N
        jMenuItem2.setText("Teoria");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        ALGEBRA.add(jMenuItem2);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lapiz.png"))); // NOI18N
        jMenuItem3.setText("Aplicaciones");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        ALGEBRA.add(jMenuItem3);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/algebra.png"))); // NOI18N
        jMenuItem1.setText("Sistemas de ecuaciones");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        ALGEBRA.add(jMenuItem1);

        jMenuBar1.add(ALGEBRA);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SIITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIITActionPerformed
        try {
            Desktop.getDesktop().browse(new URI("https://siit.itdurango.edu.mx/sistema/modulos/alu/"));
        } catch (IOException | URISyntaxException e1) {
        }
    }//GEN-LAST:event_SIITActionPerformed

    private void SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALIRActionPerformed
        Inicio obj = new Inicio();
        obj.setVisible(true);
        dispose();
        setLocationRelativeTo(null);
    }//GEN-LAST:event_SALIRActionPerformed

    private void TEORIAFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEORIAFActionPerformed
        TeoriaF obj = new TeoriaF();
        obj.setVisible(true);
        dispose();
        setLocationRelativeTo(null);
    }//GEN-LAST:event_TEORIAFActionPerformed

    private void INFOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INFOActionPerformed
        JOptionPane.showMessageDialog(null, "Proyecto desarrollado por: Corral García Oswaldo Manuel; 22041311. Todos los derechos reservados.", "Acerca de...", EXIT_ON_CLOSE);
    }//GEN-LAST:event_INFOActionPerformed

    private void GRAFICADORAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GRAFICADORAActionPerformed
        Funciones.GraficadorF obj = new GraficadorF();
        obj.setVisible(true);
        dispose();
        setLocationRelativeTo(null);
    }//GEN-LAST:event_GRAFICADORAActionPerformed

    private void TRIANGULOIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TRIANGULOIActionPerformed
        dispose();
        TrianguloInteractivoT.main(new String[0]);
    }//GEN-LAST:event_TRIANGULOIActionPerformed

    private void APLICACIONESTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_APLICACIONESTActionPerformed
        AplicacionesT obj = new AplicacionesT();
        dispose();
        obj.setVisible(true);
        setLocationRelativeTo(null);
    }//GEN-LAST:event_APLICACIONESTActionPerformed

    private void APLICACIONESFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_APLICACIONESFActionPerformed
        AplicacionesF obj = new AplicacionesF();
        dispose();
        obj.setVisible(true);
        setLocationRelativeTo(null);
    }//GEN-LAST:event_APLICACIONESFActionPerformed

    private void TEORIATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEORIATActionPerformed
        TeoriaT obj = new TeoriaT();
        dispose();
        obj.setVisible(true);
        setLocationRelativeTo(null);
    }//GEN-LAST:event_TEORIATActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        MatricesA obj = new MatricesA();
        dispose();
        obj.setVisible(true);
        setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        TeoriaA obj = new TeoriaA();
        dispose();
        obj.setVisible(true);
        setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        AplicacionesA obj = new AplicacionesA();
        dispose();
        obj.setVisible(true);
        setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ALGEBRA;
    private javax.swing.JMenuItem APLICACIONESF;
    private javax.swing.JMenuItem APLICACIONEST;
    private javax.swing.JMenu FUNCIONES;
    private javax.swing.JMenu GENERAL;
    private javax.swing.JMenuItem GRAFICADORA;
    private javax.swing.JMenuItem INFO;
    private javax.swing.JMenuItem SALIR;
    private javax.swing.JMenuItem SIIT;
    private javax.swing.JMenuItem TEORIAF;
    private javax.swing.JMenuItem TEORIAT;
    private javax.swing.JMenuItem TRIANGULOI;
    private javax.swing.JMenu TRIGONOMETRIA;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    // End of variables declaration//GEN-END:variables
}
