/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Funciones;

import GraficarFunciones.Absoluto;
import GraficarFunciones.Constante;
import GraficarFunciones.Coseno;
import GraficarFunciones.Cuadratica;
import GraficarFunciones.Cubica;
import GraficarFunciones.Exponencial;
import GraficarFunciones.Lineal;
import GraficarFunciones.Plano;
import GraficarFunciones.Racional;
import GraficarFunciones.Seno;
import Intefaz.MenuPrincipal;
import javax.swing.JToggleButton;

/**
 *
 * @author OMCG1
 */
public class GraficadorF extends javax.swing.JFrame {
    
    private String texto1 = "En esta graficadora puedes solicitar la graficación de funciones simples, vistas comunmente en matemáticas."
            + " Haz clic izquierdo en el plano cartesiano para ampliar la función, haz clic derecho para deshacer la ampliación.";
    
    private String texto = "En matemáticas, la gráfica de una función es un tipo de representación gráfica que permite conocer intuitivamente"
            + " el comportamiento de dicha función.";
    
    public String StringHTML(String texto) {
        return "<html><p>" + texto + "</p></html>";
    }
    
    private int escala = 20;

    /**
     * Creates new form Graficador
     */
    public GraficadorF() {
        initComponents();
        lblDOS.setText(StringHTML(texto1));
        lblGRAF.setVisible(false);
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnCubica = new javax.swing.JToggleButton();
        btnCuadratica = new javax.swing.JToggleButton();
        btnLineal = new javax.swing.JToggleButton();
        btnCoseno = new javax.swing.JToggleButton();
        btnSeno = new javax.swing.JToggleButton();
        btnExponencial = new javax.swing.JToggleButton();
        btnRacional = new javax.swing.JToggleButton();
        btnAbsoluto = new javax.swing.JToggleButton();
        btnConstante = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        lblUNO = new javax.swing.JLabel();
        btnUNO = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblDOS = new javax.swing.JLabel();
        lblGRAF = new javax.swing.JLabel();
        btnMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Graficador");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 400));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        buttonGroup1.add(btnCubica);
        btnCubica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CUBO.png"))); // NOI18N
        btnCubica.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Graficar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        btnCubica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCubicaActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnCuadratica);
        btnCuadratica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CUADRADO.png"))); // NOI18N
        btnCuadratica.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Graficar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        btnCuadratica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuadraticaActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnLineal);
        btnLineal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LINEAL.png"))); // NOI18N
        btnLineal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Graficar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        btnLineal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLinealActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnCoseno);
        btnCoseno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/COSENO.png"))); // NOI18N
        btnCoseno.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Graficar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        btnCoseno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCosenoActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnSeno);
        btnSeno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SENO.png"))); // NOI18N
        btnSeno.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Graficar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        btnSeno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSenoActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnExponencial);
        btnExponencial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EXPONENCIAL.png"))); // NOI18N
        btnExponencial.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Graficar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        btnExponencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExponencialActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnRacional);
        btnRacional.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/RACIONAL.png"))); // NOI18N
        btnRacional.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Graficar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        btnRacional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRacionalActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnAbsoluto);
        btnAbsoluto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ABSOLUTO.png"))); // NOI18N
        btnAbsoluto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Graficar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        btnAbsoluto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbsolutoActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnConstante);
        btnConstante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CONSTANTE.png"))); // NOI18N
        btnConstante.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Graficar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        btnConstante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConstanteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel1.setText("GRAFICADORA DE FUNCIONES SIMPLES");

        lblUNO.setText("  ");

        btnUNO.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUNO.setText("¿Qué es la gráfica de una función ?");
        btnUNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUNOActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Instrucciones");

        lblDOS.setText("jLabel3");

        lblGRAF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GRAF.png"))); // NOI18N

        btnMenu.setText("Volver al menú");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnMenu)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnLineal)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnCuadratica))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(btnRacional)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnAbsoluto))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnSeno)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnCoseno)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnCubica)
                                            .addComponent(btnExponencial)
                                            .addComponent(btnConstante))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnUNO, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblUNO, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(lblDOS, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblGRAF))))
                        .addContainerGap(32, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCuadratica)
                            .addComponent(btnLineal)
                            .addComponent(btnCubica))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnExponencial)
                                .addComponent(btnSeno, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(btnCoseno))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRacional)
                            .addComponent(btnAbsoluto)
                            .addComponent(btnConstante)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDOS)
                        .addGap(61, 61, 61)
                        .addComponent(btnUNO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblUNO, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblGRAF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMenu)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // 1 izquierdo
        // 3 derecho
        if (btnCuadratica.isSelected()) {
            
            if (evt.getButton() == 1) {
                escala++;
            } else if (evt.getButton() == 3) {
                escala--;
            }
            
            Plano panela = new Plano(this.jPanel1, escala);
            panela.Dibujar();
            Cuadratica.Dibujar(panela);
            
        }
        if (btnCubica.isSelected()) {
            
            if (evt.getButton() == 1) {
                escala++;
            } else if (evt.getButton() == 3) {
                escala--;
            }
            
            Plano panela = new Plano(this.jPanel1, escala);
            panela.Dibujar();
            Cubica.Dibujar(panela);
            
        }
        
        if (btnLineal.isSelected()) {
            
            if (evt.getButton() == 1) {
                escala++;
            } else if (evt.getButton() == 3) {
                escala--;
            }
            
            Plano panela = new Plano(this.jPanel1, escala);
            panela.Dibujar();
            Lineal.Dibujar(panela);
            
        }
        
        if (btnSeno.isSelected()) {
            
            if (evt.getButton() == 1) {
                escala++;
            } else if (evt.getButton() == 3) {
                escala--;
            }
            
            Plano panela = new Plano(this.jPanel1, escala);
            panela.Dibujar();
            Seno.Dibujar(panela);
            
        }
        
        if (btnCoseno.isSelected()) {
            
            if (evt.getButton() == 1) {
                escala++;
            } else if (evt.getButton() == 3) {
                escala--;
            }
            
            Plano panela = new Plano(this.jPanel1, escala);
            panela.Dibujar();
            Coseno.Dibujar(panela);
            
        }
        
        if (btnExponencial.isSelected()) {
            
            if (evt.getButton() == 1) {
                escala++;
            } else if (evt.getButton() == 3) {
                escala--;
            }
            
            Plano panela = new Plano(this.jPanel1, escala);
            panela.Dibujar();
            Exponencial.Dibujar(panela);
            
        }
        
        if (btnRacional.isSelected()) {
            
            if (evt.getButton() == 1) {
                escala++;
            } else if (evt.getButton() == 3) {
                escala--;
            }
            
            Plano panela = new Plano(this.jPanel1, escala);
            panela.Dibujar();
            Racional.Dibujar(panela);
            
        }
        
        if (btnAbsoluto.isSelected()) {
            
            if (evt.getButton() == 1) {
                escala++;
            } else if (evt.getButton() == 3) {
                escala--;
            }
            
            Plano panela = new Plano(this.jPanel1, escala);
            panela.Dibujar();
            Absoluto.Dibujar(panela);
            
        }
        
        if (btnConstante.isSelected()) {
            
            if (evt.getButton() == 1) {
                escala++;
            } else if (evt.getButton() == 3) {
                escala--;
            }
            
            Plano panela = new Plano(this.jPanel1, escala);
            panela.Dibujar();
            Constante.Dibujar(panela);
            
        }
    }//GEN-LAST:event_jPanel1MouseClicked

    private void btnCubicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCubicaActionPerformed
        JToggleButton btn = (JToggleButton) evt.getSource();
        if (btn.isSelected()) {
            Plano panela = new Plano(this.jPanel1, escala);
            panela.Dibujar();
            Cubica.Dibujar(panela);
        }
    }//GEN-LAST:event_btnCubicaActionPerformed

    private void btnCuadraticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuadraticaActionPerformed
        JToggleButton btn = (JToggleButton) evt.getSource();
        if (btn.isSelected()) {
            Plano panela = new Plano(this.jPanel1, escala);
            panela.Dibujar();
            Cuadratica.Dibujar(panela);
        }
    }//GEN-LAST:event_btnCuadraticaActionPerformed

    private void btnLinealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLinealActionPerformed
        JToggleButton btn = (JToggleButton) evt.getSource();
        if (btn.isSelected()) {
            Plano panela = new Plano(this.jPanel1, escala);
            panela.Dibujar();
            Lineal.Dibujar(panela);
        }
    }//GEN-LAST:event_btnLinealActionPerformed

    private void btnCosenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCosenoActionPerformed
        JToggleButton btn = (JToggleButton) evt.getSource();
        if (btn.isSelected()) {
            Plano panela = new Plano(this.jPanel1, escala);
            panela.Dibujar();
            Coseno.Dibujar(panela);
        }
    }//GEN-LAST:event_btnCosenoActionPerformed

    private void btnSenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSenoActionPerformed
        JToggleButton btn = (JToggleButton) evt.getSource();
        if (btn.isSelected()) {
            Plano panela = new Plano(this.jPanel1, escala);
            panela.Dibujar();
            Seno.Dibujar(panela);
        }
    }//GEN-LAST:event_btnSenoActionPerformed

    private void btnExponencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExponencialActionPerformed
        JToggleButton btn = (JToggleButton) evt.getSource();
        if (btn.isSelected()) {
            Plano panela = new Plano(this.jPanel1, escala);
            panela.Dibujar();
            Exponencial.Dibujar(panela);
        }
    }//GEN-LAST:event_btnExponencialActionPerformed

    private void btnRacionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRacionalActionPerformed
        JToggleButton btn = (JToggleButton) evt.getSource();
        if (btn.isSelected()) {
            Plano panela = new Plano(this.jPanel1, escala);
            panela.Dibujar();
            Racional.Dibujar(panela);
        }
    }//GEN-LAST:event_btnRacionalActionPerformed

    private void btnAbsolutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbsolutoActionPerformed
        JToggleButton btn = (JToggleButton) evt.getSource();
        if (btn.isSelected()) {
            Plano panela = new Plano(this.jPanel1, escala);
            panela.Dibujar();
            Absoluto.Dibujar(panela);
        }
    }//GEN-LAST:event_btnAbsolutoActionPerformed

    private void btnConstanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConstanteActionPerformed
        JToggleButton btn = (JToggleButton) evt.getSource();
        if (btn.isSelected()) {
            Plano panela = new Plano(this.jPanel1, escala);
            panela.Dibujar();
            Constante.Dibujar(panela);
        }
    }//GEN-LAST:event_btnConstanteActionPerformed

    private void btnUNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUNOActionPerformed
        lblUNO.setText(StringHTML(texto));
        lblGRAF.setVisible(true);
    }//GEN-LAST:event_btnUNOActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        MenuPrincipal obj = new MenuPrincipal();
        obj.setVisible(true);
        dispose();
        setLocationRelativeTo(null);
    }//GEN-LAST:event_btnMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraficadorF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraficadorF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraficadorF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraficadorF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GraficadorF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAbsoluto;
    private javax.swing.JToggleButton btnConstante;
    private javax.swing.JToggleButton btnCoseno;
    private javax.swing.JToggleButton btnCuadratica;
    private javax.swing.JToggleButton btnCubica;
    private javax.swing.JToggleButton btnExponencial;
    private javax.swing.JToggleButton btnLineal;
    private javax.swing.JButton btnMenu;
    private javax.swing.JToggleButton btnRacional;
    private javax.swing.JToggleButton btnSeno;
    private javax.swing.JButton btnUNO;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDOS;
    private javax.swing.JLabel lblGRAF;
    private javax.swing.JLabel lblUNO;
    // End of variables declaration//GEN-END:variables
}
